adelsz/pgtyped

package-lock.json
packages/cli/README.md
packages/cli/package-lock.json
packages/cli/src/config.ts
packages/cli/src/index.ts
packages/example/Dockerfile
packages/example/README.md
packages/example/config.json
packages/example/docker-compose.yml
packages/example/package-lock.json
packages/example/sql/schema.sql
packages/example/src/books/queries.types.ts
packages/example/src/users/queries.types.ts
packages/example/stack.yml
packages/query/package-lock.json
packages/query/src/actions.test.ts
packages/query/src/actions.ts
packages/wire/package-lock.json
packages/wire/src/helpers.ts
packages/wire/src/messages.ts
packages/wire/src/protocol.ts

- Added support for both MD5 and cleartext password authentication.
- Wrapped example package in a docker container to simplify starting the example demo

Add password support and better usage example

---

packages/cli/src/generator.ts

Adds baked-in support for most primitive PostgreSQL types

Support more PG types

---

packages/cli/src/index.ts

Skip in-scope files with no gql tags

---

README.md
packages/cli/README.md
packages/cli/src/config.ts
packages/cli/src/index.ts
packages/query/src/actions.ts
packages/wire/src/queue.ts

Changes:
* Adds `port` setting to config
* Support `PGHOST`, `PGUSER`, `PGPASSWORD`, `PGDATABASE` and `PGPORT` configuration options
* Improve error reporting on CLI startup
Fixes #39 
Fixes #35

Improve CLI configuration options

---

packages/example/config.json
packages/example/src/index.ts
packages/example/src/notifications/notifications.ts
packages/example/src/notifications/notifications.types.ts
packages/query/src/preprocessor.ts

Add test case for order-dependence of parameters

---

README.md
packages/cli/README.md
packages/cli/src/config.ts
packages/cli/src/index.ts

fail-on-error
Signed-off-by: Silas Davis <silas@monax.io>

Fix another unhandled exception and provide early fatal failure via

---

packages/cli/src/types.ts

Signed-off-by: Silas Davis <silas@monax.io>

Support intervals

---

.github/workflows/main.yml
packages/cli/src/__snapshots__/generator.test.ts.snap
packages/cli/src/generator.test.ts
packages/cli/src/generator.ts
packages/example/src/notifications/notifications.ts
packages/example/src/notifications/notifications.types.ts
packages/example/src/users/sample.types.ts
packages/query/src/actions.ts
packages/query/src/preprocessor-ts.test.ts

* Fix empty query parsing for TS queries
* Make nested parameters nullable by default
* Update GH action triggers

Improve query parsing

---

packages/cli/src/config.ts

Config parser now accepts absolute file paths

---

docs-new/docs/ts-file-intro.md
docs-new/docs/ts-file.md

That's just a small cheatsheet that I've created for myself when I was working with pgtyped.
I'm not sure which part of the documentation would be best for it, but hopefully this compressed list of all types of different parameter substitutions would turn out helpful for other users.

Parameter substitution cheatsheet

---

docs-new/docs/cli.md
packages/cli/src/index.ts

File parameter override

---

packages/cli/src/types.ts
packages/example/package-lock.json
packages/example/package.json
packages/example/src/books/books.queries.ts
packages/example/src/books/books.sql
packages/example/src/comments/comments.queries.ts
packages/example/src/index.ts
packages/example/src/notifications/notifications.queries.ts
packages/example/src/notifications/notifications.types.ts
packages/example/src/users/sample.types.ts

Fixes #95
Fixes #144
Note to reviewer: Diff looks bigger is, hide whitespace in Github UI to see actual diff

Add support for Array types

---

packages/example/src/books/books.queries.ts
packages/example/src/books/books.sql
packages/query/src/loader/sql/__snapshots__/index.test.ts.snap
packages/query/src/loader/sql/grammar/SQLParser.g4
packages/query/src/loader/sql/index.test.ts
packages/query/src/loader/sql/index.ts
packages/query/src/loader/sql/parser/SQLParser.ts

Ignore multiline comments inside SQL statements

---

packages/cli/src/generator.test.ts
packages/cli/src/types.ts
packages/example/src/books/books.queries.ts
packages/example/src/comments/comments.queries.ts
packages/example/src/notifications/notifications.queries.ts
packages/example/src/notifications/notifications.types.ts

sorts all generated types so that type file generation will be deterministic

---

packages/cli/src/index.ts

Small pretty self-explanatory fix. 😃

Add CLI flags `--watch` and `--file` as defined in help message

---

docs-new/docs/cli.md
packages/cli/package-lock.json
packages/cli/package.json
packages/cli/src/config.ts
packages/cli/src/index.ts
packages/example/config.json
packages/example/docker-compose.yml

Add better CLI arg support using yargs

---

packages/query/src/actions.ts
packages/query/src/loader/typescript/index.ts

This would resolve this issue: https://github.com/adelsz/pgtyped/issues/328

Use wildcard import to enable compatibility with esModuleInterop false

---

packages/cli/src/generator.ts
packages/cli/src/index.ts
packages/cli/src/types.ts
packages/cli/src/util.ts
packages/query/src/actions.ts
packages/query/src/loader/sql/index.ts
packages/query/src/loader/sql/logger.ts
packages/query/src/loader/sql/parser/SQLLexer.ts
packages/query/src/loader/typescript/query.ts
packages/query/src/preprocessor-ts.test.ts
packages/query/src/preprocessor.ts
packages/query/src/tag.ts
packages/wire/src/helpers.ts
packages/wire/src/messages.ts
packages/wire/src/protocol.test.ts
packages/wire/src/queue.ts
tslint.json

Removes some dead code that isn't used (in the spirit of trying to improve on-boarding to the code base).

Remove unused code

---

.github/workflows/main.yml
packages/example/Dockerfile
packages/example/docker-compose.yml

Testing more than just the most-recent node version is important for package adoption. All the important recent releases are now tested with this PR
Graph from https://nodejs.org/en/about/releases/

Test all recent node versions

---

packages/cli/src/worker.ts

feat: \n line endings in generated IRs

---

docs-new/README.md
docs-new/docs/dynamic-queries.md

Hi, I accidentally closed my previous PR while I was trying to update the branch, so I created one again. Unlike previous PR, this time there were only 2 changes.
1. README - where I change `yarn` keyword to `npm`, since `package-lock.json` is used
2. Docs - added casting for Dynamic Queries to improve clarity
Below are the differences in the docs generated. Look forward to your reply and perhaps the merge of my PR to main branch. Thank you
|Before|After|
|:---|:---|
|![before](https://user-images.githubusercontent.com/53143214/167180947-05149bbe-02c2-401a-a67e-24d23ce2c8bf.png)| ![after](https://user-images.githubusercontent.com/53143214/167235677-f92f6acf-0304-4a04-adeb-050c905ada28.png)|

chore(dynamic-queries): added casting for `IS NULL` section of Dynamic Queries & replace `yarn` in `README` with `npm`

---

packages/cli/src/types.test.ts
packages/cli/src/types.ts

fix: emit Json type when required by JsonArray

---

packages/cli/src/config.ts
packages/cli/src/generator.test.ts
packages/cli/src/generator.ts

Fixes issue https://github.com/adelsz/pgtyped/issues/379

config switch for Hungarian notation on interface names

---

packages/query/src/actions.ts

Fixes https://github.com/adelsz/pgtyped/issues/501

Add support for cleartext password authentication

---

packages/cli/src/index.ts

See investigation [here](https://github.com/adelsz/pgtyped/issues/262#issuecomment-2492838066)
I hope this is a small enough PR to easily review and release

1-line change to fix Deno support

---

package-lock.json
package.json
packages/cli/package.json
packages/cli/src/typescriptAndSqlTransformer.ts

Fix chokidar glob
