README.md, packages/cli/src/generator.test.ts, packages/cli/src/generator.ts, packages/example/src/books/queries.ts, packages/example/src/books/queries.types.ts, packages/example/src/users/queries.ts, packages/example/src/users/queries.types.ts, packages/query/src/tag.ts, tslint.json
Make `sql` tag to expect one generic parameter instead of two:
```diff
- export const selectUserIds = sql<
-   ISelectUserIdsResult, ISelectUserIdsParams
-   >`select id from users where id = $id and age = $age`;
- `;
+ export const selectUserIds =
+  sql<ISelectUserIdsQuery>`select id from users where id = $id and age = $age`;
```
=> Simplify tag generics

packages/cli/package-lock.json, packages/cli/src/generator.test.ts, packages/cli/src/generator.ts, packages/cli/src/index.ts, packages/cli/src/types.ts, packages/example/docker-compose.yml, packages/example/sql/schema.sql, packages/example/src/books/books.queries.ts, packages/example/src/comments/comments.queries.ts, packages/example/src/index.ts, packages/example/src/notifications/notifications.queries.ts, packages/example/src/notifications/notifications.sql, packages/query/package-lock.json, packages/query/src/actions.ts
This only has a basic unit test. I was going to add something to example package just so i could test it. is there anywhere else for an integration test?
I've given a nod to your suggestion that people may want different type aliases with my refactor of the type mapping. Currently this allows you to provide an alternative name and optional definition. I thought it might be useful to allow imports to external types to be dragged in but in some ways it's nice to keep it local.
fixes #45
=> Implement postgres types for JSON, timestamps, and bytes

.github/workflows/main.yml, docs/annotated-sql.md, packages/cli/src/config.ts, packages/cli/src/generator.test.ts, packages/cli/src/generator.ts, packages/cli/src/index.ts, packages/cli/src/types.test.ts, packages/cli/src/types.ts, packages/example/config.json, packages/example/docker-compose.yml, packages/example/package-lock.json, packages/example/sql/schema.sql, packages/example/src/books/books.queries.ts, packages/example/src/comments/comments.queries.ts, packages/example/src/index.ts, packages/example/src/notifications/notifications.queries.ts, packages/example/src/notifications/notifications.sql, packages/example/src/users/sample.types.ts, packages/query/src/__snapshots__/actions.test.ts.snap, packages/query/src/actions.test.ts, packages/query/src/actions.ts, packages/query/src/type.ts
This allows pgtyped to generate code from queries involving database
enum types. The postgres enums will be converted to a string-valued const enum
in the generated code.
The `getTypes` reflection query now joins on pg_enum and accumulates
enum information as it collects other type information. I think it may
be possible to accomodate composite types by aggregating over the object
graph given by a suitable join query in a similar way.
@pgtyped/query now returns `MappableTypes` which are either a string
referencing a database type name or a fully-described `Type`. `Type` now
includes `EnumType`. This allows type definitions to be realised at
different stages in the reflection/mapping process and should allow for
custom overrides in config.
fixes #54
=> Implement support for Postgres enums

packages/cli/src/generator.test.ts, packages/cli/src/generator.ts, packages/cli/src/types.ts
Accidentally forgot to pass types to TS generation.
Removed default parameter to avoid this happening and run generator tests against both generations regimes systematically.
=> Emit type declarations for Typescript too (oops)

.github/workflows/main.yml, package-lock.json, package.json, packages/cli/src/generator.test.ts, packages/cli/src/types.ts, packages/example/Dockerfile, packages/example/README.md, packages/example/docker-compose.yml, packages/example/package-lock.json, packages/example/package.json, packages/example/scripts/wait-for-postgres-then, packages/example/src/index.ts, packages/example/src/notifications/notifications.queries.ts
This provides assignability between enum-mapped types from different
query files where Typescript enums would be incompatible.
Also harness up pacakges/example as a form of integration/smoke test in
CI.
fixes #65
=> Use unions to represent Postgres enum types

README.md
This is done in order to adhere to `node-postgres` simple example as can be seen here - https://github.com/brianc/node-postgres-docs/blob/master/content/welcome.mdx#getting-started
=> Disconnect client in example

packages/cli/src/types.ts
https://www.postgresql.org/docs/current/citext.html
https://www.postgresql.org/docs/current/datatype-net-types.html
I also have some functions with a return type of `void` which this pull request helps support.
=> Add citext, network, and void types

packages/cli/src/config.ts
It also makes it possible to use .ts file through ts-node:
`ts-node ./node_modules/.bin/pgtyped -w -c pgtypedconfig.ts`
=> Allow for config to be a JS file

packages/cli/src/types.ts
bpchar (blank padded char) is the internal name of char and without this the cli fails, because the type is not known
https://stackoverflow.com/questions/51421269/why-char-datatype-is-converted-to-bpchar-automatically
=> extend types with bpchar

packages/cli/package.json
it is deprecated
follow up on https://github.com/adelsz/pgtyped/issues/135
@adelsz how can I use the dependencies bot to update `package.lock` ?
=> remove @types/camel-case

packages/query/src/tag.ts
I found myself writing a piece of code that looked like this:
```Typescript
async function doSomeDbRelatedTask(db?: IDatabaseConnection): Promise<void> {
db = db || postgres
await someQuery.run({ someParams }, db)
}
```
Which can work inside a given transaction or on it's own. `postgres` is a global db connection that has type [`Pool`](https://node-postgres.com/api/pool), but when this is used inside a transaction, I provide an argument of type [`PoolClient`](https://node-postgres.com/api/client).
Naturally, I want to use some type to describe them both in my code, and `IDatabaseConnection` is exactly what I need, so why not make it public so I can use it in my code?
=> Exporting IDatabaseConnection

packages/cli/src/generator.test.ts, packages/cli/src/generator.ts
This updates the generated array types from `Array<T>` to `readonly T[]`
Since the arrays passed in to the generated functions are not being mutated, it would be nice if they were typed as `readonly` so that consumers with a readonly array can use that array as an arg w/o cloning it.
=> make params that are arrays readonly in ts

docs-new/docs/cli.md, packages/cli/src/config.ts, packages/query/src/actions.ts, packages/wire/src/messages.ts, packages/wire/src/queue.ts
This adds support for SSL connections.
You can provide SSL options in the db config:
Providing certificate to verify SSL/TLS
```
ssl: {
host: "insert IP of remote database",
port: 5432,
ca: ["insert ca cert here"],
}
```
Ignoring SSL/TLS errors; allows for MITM attacks to occur
or 
```
"ssl": {
"rejectUnauthorized": false
}
```
or 
Checks local certificate
```
"ssl": true
```
=> Add support for SSL

docs-new/docs/cli.md, packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/config.ts
Database URLs are a common way to connect to databases, and supporting them is helpful to end users.
=> Allow db config to be provided as a URL

package-lock.json, packages/query/package-lock.json, packages/query/package.json, packages/query/src/loader/sql/parser/SQLLexer.ts, packages/query/src/loader/sql/parser/SQLParser.ts, packages/query/src/loader/sql/parser/SQLParserListener.ts, packages/query/src/loader/sql/parser/SQLParserVisitor.ts, packages/query/src/loader/typescript/parser/QueryLexer.ts, packages/query/src/loader/typescript/parser/QueryParser.ts, packages/query/src/loader/typescript/parser/QueryParserListener.ts, packages/query/src/loader/typescript/parser/QueryParserVisitor.ts
When using this package in a Yarn V2 project the following error occurs because of circular references in the `antlr4ts` dependency:
```
class XPathLexer extends __2.Lexer {
^
TypeError: Class extends value undefined is not a constructor or null
at Object.<anonymous> (app/node_modules/antlr4ts/dist/tree/xpath/XPathLexer.js:9:30)
at Module._compile (node:internal/modules/cjs/loader:1092:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
at Module.load (node:internal/modules/cjs/loader:972:32)
at Function.external_module_.Module._load (.pnp.js:52489:14)
at Module.require (node:internal/modules/cjs/loader:996:19)
at require (node:internal/modules/cjs/helpers:92:18)
at Object.<anonymous> (app/node_modules/antlr4ts/dist/tree/xpath/XPath.js:13:22)
at Module._compile …
```
=> Fix `antlr4ts` crash when using Yarn V2

packages/cli/package-lock.json, packages/cli/package.json, packages/cli/src/index.ts
When emitting files in a directory other than the source directory the write can fail if the intermediary directories does not exist. This uses [outputFile](https://github.com/jprichardson/node-fs-extra/blob/master/docs/outputFile.md) from fs-extra which creates directories if needed.
=> Create directories when writing files

packages/cli/src/index.ts
This is useful in conjunction with tools like nodemon that monitor for
file changes. By only writing files if the content has actually changed,
unnecessary side effects (like nodemon restarting) can be avoided.
Fixes #257
=> feat: only write files if the content differs

packages/cli/src/generator.test.ts
The mocked values don't line up with the SQL. This change doesn't fix any behaviour, but it makes the tests easier to understand.
=> Fix mocked values in generator tests

packages/cli/src/types.ts
Numeric/decimal values are returned as strings by node-postgres
because they can exceed `Number.MAX_SAFE_INTEGER`.
=> Cast numeric/decimal/money as a string

packages/example/package.json
Otherwise they will keep running (I discovered that when I tried starting my own PostgreSQL and the port was blocked).
=> Remove docker-compose containers and network after tests

packages/cli/src/types.ts
fixes #315
I've just taken a pot shot here, looking for some initial feedback. Is it this simple?
=> Add `name` to type mapping

packages/cli/src/types.ts
This PR simply adds an extra type to `cli/src/types.ts`, for the Postgis column type `point`. The type is a `number[]`. Technically it could be typed more strictly as `[number, number]`, but I believe that would involve more significant changes to pgTyped, and this is perfectly acceptable for our purposes. 
I have tested this by building the code and linking the `@pgtyped/cli` package to my application. It successfully removes the `column type not supported by mapping` errors that I was seeing before. 
Apologies if I have missed anything. Let me know if there are any further changes to make! Thank you.
This is a rudimentary solution to the issue discussed in #232, although only for the `point` type. I would be happy to add more Postgis types if there is demand for it.
=> add Postgis Point type as number[]

packages/cli/src/generator.test.ts, packages/cli/src/generator.ts, packages/example/src/books/books.queries.ts, packages/example/src/comments/comments.queries.ts, packages/example/src/notifications/notifications.queries.ts, packages/example/src/notifications/notifications.types.ts, packages/example/src/users/sample.types.ts
Basically copy-paste of #204 
Our team uses pgtyped and we are getting lots of churn on pull requests and in git because the ordering of fields isn't deterministic. (depends on layout of fields in the database -- which can be different if some people applied migrations in different orders or rolled-back at some point in time).
This is a PR to sort the field names alphabetically.
=> sorted generator fields

packages/cli/src/types.ts
I would like to use TSTZRange types in my pgtyped queries. Pgtyped should allow users to use unsupported types through calling them unknown.
=> Use unknown instead of never

packages/cli/.npmignore, packages/query/.npmignore, packages/wire/.npmignore
The added .npmignore has exclude patterns to remove files from the
package that's published to NPM. The patterns are targeting
development-only files, i.e. TypeScript sources, tests, tsconfig.json
=> Add .npmignore to slim packages

packages/cli/src/types.ts
This PR adds support for queries returning `tsvector`, by declaring that the value is encoded as a string. This is true at least when the pg library is used:
```sql
select to_tsvector('the cat ate the hat');
```
returns
```ts
{"to_tsvector": "'ate':3 'cat':2 'hat':5"}
```
=> Add type mapping support for tsvector

packages/cli/src/generator.ts, packages/example/src/books/books.queries.ts, packages/example/src/comments/comments.queries.ts, packages/example/src/notifications/notifications.queries.ts, packages/query/src/index.ts, packages/query/src/loader/sql/index.ts, packages/query/src/preprocessor-sql.test.ts, packages/query/src/preprocessor-sql.ts, packages/query/src/tag.ts
Previously the query AST was used as the IR, which was functional, but
contained absolute line numbers and character offsets that would change
any time queries earlier in the file were changed. This made conflict
resolution particularly painful and would generally result in merge
conflicts.
Fixes adelsz/pgtyped#398
The strategy here is to introduce a dedicated IR interface rather than just using the AST structure. The dedicated IR structure removes unnecessary data, and normalizes the locations to be relative to the start of the query, rather than the start of the file. This means changes to queries don't cause side effects to other queries.
=> Introduce more stable SQL query IR

docs-new/docs/cli.md, packages/cli/src/config.ts, packages/cli/src/generator.ts, packages/cli/src/worker.ts
Fix #475
A very straight forward PR that allows users to override some default Postgres type mapping. See #475 for a concreate example.
=> Add types overrides

packages/cli/src/generator.test.ts, packages/cli/src/generator.ts, packages/example/src/__snapshots__/index.test.ts.snap, packages/example/src/books/books.queries.ts, packages/example/src/books/books.sql, packages/example/src/index.test.ts, packages/example/src/notifications/notifications.queries.ts
Nullable scalar parameters can now be omitted from parameter objects:
```diff
export interface IGetNotificationsParams {
-  userId: string | null | void;
+  userId?: string | null | void;
}
```
Meaning you no longer have to pass `undefined` explicitly to such queries:
```diff
const result = findBookNameOrRank.run({
rank: 1,
- name: undefined
}, client);
```
=> feat!: make nullable scalar parameters optional

docs-new/docs/cli.md, packages/cli/src/config.ts
=> Add support for DATABASE_URL as an alternative to PGURI

package.json, packages/example/sql/schema.sql, packages/example/src/books/books.queries.ts, packages/example/src/books/books.sql, packages/query/src/actions.ts, packages/wire/src/protocol.test.ts, packages/wire/src/protocol.ts, packages/wire/src/queue.ts
This fixes an issue with handling of fragmented TCP packets.
The problem was uncovered in https://github.com/adelsz/pgtyped/issues/474. The type inference query result for such a big enum sometimes doesn't fit into a single TCP packet so it gets split into two, with the boundary cutting a PGSQL protocol frame in half.
Solution is to concat TCP packets into a single Buffer as we receive them to make them continuous for the parsing routines. Memory is cleaned up by unreferencing the Buffer on PGSQL frame boundaries.
=> Fix fragmented TCP packet handling

docs-new/docs/cli.md, docs-new/docs/typing.md, docs-new/sidebars.js, packages/cli/src/config.ts, packages/cli/src/declareImport.test.ts, packages/cli/src/generator.test.ts, packages/cli/src/generator.ts, packages/cli/src/stringToType.test.ts, packages/cli/src/types.test.ts, packages/cli/src/types.ts, packages/cli/src/worker.ts, packages/query/src/index.ts, packages/query/src/type.ts
Fix #480 
Please review it carefully, I did not test it end to end.
=> Types overrides imports

packages/cli/src/types.ts, packages/example/config.json, packages/example/src/books/books.queries.ts, packages/example/src/books/books.sql, packages/example/src/customTypes.ts, packages/example/src/index.test.ts, packages/example/src/notifications/notifications.queries.ts, packages/example/src/notifications/notifications.sql
- I added some examples to the example app.
- I updated the `use` method implementation to handle enums and overrides better.
=> Better types overrides for enum

packages/cli/package.json
Using yarn berry I have detected this:
```
node:internal/event_target:1010
process.nextTick(() => { throw err; });
^
Error: @pgtyped/cli tried to access @pgtyped/parser, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
Required package: @pgtyped/parser (via "@pgtyped/parser/package.json")
Required by: @pgtyped/cli@virtual:a0ba3d3cda9824c28dd8fd0178ccbd7bc86eb7f53d38543771df1887d0bc057caad9034577859ad1cbfd031b50c5c91f73d6ffe7e42882783fd34e4f1a7cc8fb#npm:2.1.0 (via /home/lizard/Projects/coprali/coprali-nodejs/.yarn/__virtual__/@pgtyped-cli-virtual-cee4d22642/0/cache/@pgtyped-cli-npm-2.1.0-02c65e08f0-86ee7ec2a0.zip/node_modules/@pgtyped/cli/lib/generator.js)
```
=> Missing dep

package-lock.json, package.json, packages/cli/package.json
This PR upgrades the TypeScript version to latest 5.0.4 as well as update the cli peer dependency to fix this issue: https://github.com/adelsz/pgtyped/issues/511
=> chore: upgrade TypeScript version

lerna.json, packages/cli/src/types.ts
**Describe the bug**
Generated imports for `typesOverrides`  contain backslashes instead of slashes on Windows.
Relates to https://github.com/adelsz/pgtyped/issues/519
**Expected behavior**
Backslashes are invalid in TypeScript imports, so I expect it to generate the same import (with slashes) on both Unix systems and Windows.
**Test case**
- CLI v2.2.1 on a Win 11
- Add a `typesOverrides` configuration in your project
- Then run pgtyped build.
- You will see broken imports on top of generated TypeScript files
=> fix: generate POSIX paths in typesOverrides imports

packages/cli/README.md, packages/cli/src/worker.ts
=> Added `dir_base` template parameter for `emitTemplate`

packages/wire/src/protocol.ts
Hi 👋 , this is a follow up to [this PR](https://github.com/adelsz/pgtyped/pull/487) from last year. We ran into an issue today where the `const messageSize = buf.readUInt32BE(bufferOffset);` line would cause an `ERR_OUT_OF_RANGE` error in about 1/5 executions of `pgtyped`. The error would always occur when parsing a file which referenced a large enum. The error began occurring when a change was merged to add two values to this enum. 
My suspicion is that the additional enum value has caused the boundary of the TCP packet splitting to land in the middle of the bytes making up the `messageSize` integer. The fix that I have implemented is to first check that the buffer has enough data to read the indicator and messageSize, before attempting to do so. 
I attempted to create a minimal …
=> Prevent ERR_OUT_OF_RANGE errors when reading messageSize from buffer

packages/runtime/src/tag.ts
Link to my [feature request issue](https://github.com/adelsz/pgtyped/issues/568)!
`pg-cursor` is maintained by the same author as `pg` and also part of his official documentation.
- **`pg-cursor` is documented on `README`**
https://github.com/brianc/node-postgres
- **`pg-cursor` is located in same monorepo as `pg`**
https://github.com/brianc/node-postgres/tree/master/packages/pg-cursor
- **Official `pg-cursor` documentation**
https://node-postgres.com/apis/cursor
```ts
import ( IDatabaseConnection } from "@pgtyped/runtime/lib/tag";
import { Client } from "pg";
import Cursor from "pg-cursor";
const client = new Client({ /* ... */ });
const connection: IDatabaseConnection = {
query: (query, bindings) => client.query(query, bindings),
stream: (query, bindings) => client.query(new …
```
=> feat: add support for streaming

packages/runtime/package.json
Fixes #570.
This fix was tested by applying the equivalent fix to a real project exhibiting the TypeScript issue and seeing if it would now compile (yes):
```patch
diff --git a/lib/index.d.cts b/lib/index.d.cts
new file mode 100644
index 0000000000000000000000000000000000000000..3d9337b5edcde8c7b8a98aa9cd81c6b1a1451542
--- /dev/null
+++ b/lib/index.d.cts
@@ -0,0 +1,4 @@
+export { ParameterTransform, QueryParameters, InterpolatedQuery, QueryParameter, } from './preprocessor.js';
+export { processTSQueryAST } from './preprocessor-ts.js';
+export { processSQLQueryIR } from './preprocessor-sql.js';
+export { sql, TaggedQuery, PreparedQuery } from './tag.js';
diff --git a/package.json b/package.json
index bed91dd3d360132d3e0b18375f4dc7d89cb4a10b..57491d5b4b2e6f5e87016a888a01001b8614a663 100644 …
```
=> Fix moduleResolution:node16 CommonJS compatibility

packages/runtime/src/index.ts
This type is helpful to expose to calling code.  While updating our project to ESM I noticed its not exported.
=> Export IDatabaseConnection type

packages/runtime/src/tag.ts
Resolves #590 
Because we throw away all other details of the result, this adds a new method that will be able to retain more than just the result. For now we can return the row count.
=> Feat: run method that returns affected row count

docs-new/docs/cli.md, packages/cli/src/config.ts, packages/cli/src/generator.test.ts, packages/cli/src/generator.ts
When using array parameters (including array spread and pick), providing an empty array to a parameter will usually cause a crash at runtime due to a syntax error.
For the following query, if an empty array is provided for userIds:
```
/*
@name GetNotifications
@param userIds -> (...)
*/
SELECT * FROM notifications WHERE id in :userIds!
```
As the query at runtime becomes:
```
SELECT * FROM notifications WHERE id in ()
```
Which results in:
```
ERROR:  syntax error at or near ")"
```
Therefore, this config forces the generated parameter type to only allow
non-empty arrays, i.e. the type `[T, ...T[]]` rather than `T[]`.
=> feat!: Allow enforcing non-empty array parameters in config
